# Generated by Django 3.2.2 on 2021-06-27 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('idNoticia', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50, verbose_name='Nombre Producto')),
                ('texto', models.TextField(max_length=500)),
                ('imagen', models.CharField(default='', max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.categoria')),
            ],
        ),
    ]
